from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import Table, TableStyle

def section_header(c, text, y):
    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(colors.HexColor("#1A73E8"))
    c.drawString(50, y, text)
    c.setFillColor(colors.black)
    return y - 15


def draw_table(c, data, x, y):
    table = Table(data, colWidths=[200, 200])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#E8EEF9")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#F7F9FC")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ]))

    table.wrapOn(c, x, y)
    table.drawOn(c, x, y - table._height)

    return y - table._height - 30


def generate_pdf_from_report(report, output_path):
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4
    y = height - 60

    # ---------------- HEADER ----------------
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, y, "Interview Analysis Report")
    y -= 40

    # ---------------- FACE METRICS ----------------
    y = section_header(c, "Face Metrics", y)

    face = report.get("face", {})
    face_data = [
        ["Metric", "Value"],
        ["Blink Count", face.get("blink_count")],
        ["Eye Contact (%)", face.get("eye_contact_percent")],
        ["Attention (%)", face.get("estimated_attention_percent")],
    ]

    y = draw_table(c, face_data, 50, y)

    # Emotions table
    emotions = face.get("emotion_counts", {})
    emo_rows = [["Emotion", "Count"]]
    for e, cnt in emotions.items():
        emo_rows.append([e.capitalize(), cnt])

    y = draw_table(c, emo_rows, 50, y)

    # ---------------- AUDIO METRICS ----------------
    y = section_header(c, "Audio Metrics", y)

    audio = report.get("audio", {})
    audio_data = [
        ["Metric", "Value"],
        ["Avg Energy", audio.get("avg_energy")],
        ["Avg ZCR", audio.get("avg_zcr")],
        ["Speech Duration (s)", audio.get("speech_duration")],
        ["Filler Words", audio.get("filler_word_count")],
        ["Hesitations", audio.get("hesitation_count")],
    ]

    y = draw_table(c, audio_data, 50, y)

    # ---------------- NLP METRICS ----------------
    y = section_header(c, "NLP Metrics", y)

    nlp = report.get("nlp", {})
    nlp_data = [
        ["Metric", "Value"],
        ["Word Count", nlp.get("word_count")],
        ["Keywords Found", ", ".join(nlp.get("found_keywords", []))],
        ["Final Quality Score", nlp.get("final_quality_score")],
    ]

    y = draw_table(c, nlp_data, 50, y)

    # ---------------- FINAL SCORE ----------------
    c.setFont("Helvetica-Bold", 20)
    c.setFillColor(colors.HexColor("#0B8043"))
    c.drawString(50, y, f"Final Score: {report.get('final_score')}")
    c.setFillColor(colors.black)

    # ---------------- FOOTER ----------------
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 40, "Generated by AI Interview Analyzer")

    c.save()
